[package]
name = "sample_db_1"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
diesel = { version = "2.2.0", features = ["postgres", "chrono"] }
chrono = { version = "0.4.38", features = ["serde"] }